version: "3.9"

services:
  app:
    container_name: sale_smart_ai_backend
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8065:8065" # Maps Host 8000 -> Container 8000
    volumes:
      - ./config.yml:/app/config.yml
    restart: unless-stopped